---
# Build janus-gateway
- name: Clone janus-gateway
  git:
    repo: "{{ janus_gateway_repo }}"
    dest: "{{ janus_gateway_dir }}"
    version: "{{ janus_libnice_version }}"

- name: Run janus-gateway config autogen
  command:
    cmd: sh autogen.sh
    chdir: "{{ janus_gateway_dir }}"

- name: Configure janus-gateway build
  command:
    cmd: ./configure --prefix=/opt/janus --disable-rabbitmq --disable-mqtt
    chdir: "{{ janus_gateway_dir }}"

- name: Build janus-gateway
  command:
    cmd: make
    chdir: "{{ janus_gateway_dir }}"

- name: Install janus-gateway
  command:
    cmd: make install
    chdir: "{{ janus_gateway_dir }}"

- name: Render janus-gateway config templates
  ansible.builtin.template:
    src: "{{ item.value }}"
    dest: "{{ janus_conf_dir }}{{ item.value }}"
  with_dict: "{{ janus_conf_template }}"