# tasks file for ansible-role-janus-gateway
- name: Install platform dependencies
  import_tasks: dependencies.yml
  tags:
    janus-gateway

- name: Create workspace
  ansible.builtin.file:
    path: "{{ janus_workspace_dir }}"
    state: directory
    mode: "770"
    recurse: true
    
- name: Install libnice
  import_tasks: libnice.yml
  tags:
    janus-gateway

# - name: Install usrsctp
#   import_tasks: usrsctp.yml
#   tags:
#     janus-gateway

- name: Install libwebsockets
  import_tasks: libwebsockets.yml
  tags:
    janus-gateway

- name: Install libsrtp
  import_tasks: libsrtp.yml
  tags:
    janus-gateway

# Build janus-gateway
- name: Clone janus-gateway
  git:
    repo: "{{ janus_repo }}"
    dest: "{{ janus_build_dir }}"
    version: "{{ janus_version }}"

- name: Run janus-gateway config autogen
  command:
    cmd: sh autogen.sh
    chdir: "{{ janus_build_dir }}"
  when: janus_upgrade_available

- name: Configure janus-gateway build
  command:
    cmd: "./configure \
      --prefix={{ janus_install_dir }} \
      {{ janus_build_extras.rabbitmq ? '' : '--disable-rabbitmq' }} \
      {{ janus_build_extras.mqtt ? '' : '' : --disable-mqtt }} \
      {{ janus_build_extras.websockets ? '' : ''--disable-websockets }} \
      {{ janus_build_extras.nanomsg ? '' : ''--disable-nanomsg }} \
      {{ janus_build_extras.systemd ? '--enable-systemd-sockets' : '' }} \
      {{ janus_build_extras.recordplay ? '' : '--disable-plugin-recordplay' }} \
      {{ janus_build_extras.sip ? '' : '--disable-plugin-sip' }}"
      
    chdir: "{{ janus_build_dir }}"
  when: janus_upgrade_available

- name: Build janus-gateway
  become: true
  command:
    cmd: make
    chdir: "{{ janus_build_dir }}"
  when: janus_upgrade_available

- name: Install janus-gateway
  become: true
  command:
    cmd: make install
    chdir: "{{ janus_build_dir }}"
  when: janus_upgrade_available

- name: Set installed version facts
  ansible.builtin.set_fact:
    janus_installed_versions:  
      janus: "{{ janus_version }}"
      libnice: "{{ janus_libnice_version }}"
      usrsctp: "{{ janus_usrsctp_version }}"
      libsrtp: "{{ janus_libsrtp_version }}"
      libwebsockets: "{{ janus_libwebsockets_version }}"
    cacheable: yes
