---
# Build libnice

- name: Install meson and ninja build systems
  ansible.builtin.pip:
    name:
      - meson 
    virtualenv: "{{ janus_workspace_dir }}/venv"
    virtualenv_command: /usr/bin/python3.7 -m venv

- name: Clone libnice
  git:
    repo: "{{ janus_libnice_repo }}"
    dest: "{{ janus_libnice_build_dir }}"
    version: "{{ janus_libnice_version }}"

- name: Run libnice meson build
  command:
    cmd: "meson --prefix={{ janus_lib_prefix }} build"
    chdir: "{{ janus_libnice_build_dir }}"
  when: janus_upgrade_available
  environment:
    PATH: "{{ janus_workspace_dir }}/venv/bin:{{ ansible_env.PATH }}"

- name: Configure libnice ninja build
  command:
    cmd: "ninja -C build"
    chdir: "{{ janus_libnice_build_dir }}"
  when: janus_upgrade_available
  environment:
    PATH: "{{ janus_workspace_dir }}/venv/bin:{{ ansible_env.PATH }}"

- name: Install libnice
  become: true
  command:
    cmd: "ninja -C build install"
    chdir: "{{ janus_libnice_build_dir }}"
  when: janus_upgrade_available
  environment:
    PATH: "{{ janus_workspace_dir }}/venv/bin:{{ ansible_env.PATH }}"
