---

- name: Create libsrtp workspace
  ansible.builtin.file:
    path: "{{ janus_libsrtp_build_dir }}"
    state: directory
    mode: 0644
    
- name: Download and unarchive libsrtp 
  ansible.builtin.unarchive:
    src: '{{ janus_libsrtp_tarball }}'
    dest: '{{ janus_workspace_dir }}'
    remote_src: yes

- name: Configure libsrtp
  command:
    cmd: "./configure --prefix={{ janus_lib_prefix }} --enable-openssl"
    chdir: "{{ janus_libsrtp_build_dir }}"
  when: janus_upgrade_available

- name: Build libsrtp
  command:
    cmd:  make shared_library
    chdir: "{{ janus_libsrtp_build_dir }}"
  when: janus_upgrade_available

- name: Install libsrtp
  command:
    cmd: make install
    chdir: "{{ janus_libsrtp_build_dir }}"
  when: janus_upgrade_available
