---
# Build libwebsockets
- name: Clone libwebsockets
  git:
    repo: "{{ janus_libwebsockets_repo }}"
    dest: "{{ janus_libwebsockets_build_dir }}"
    version: "{{ janus_libwebsockets_build_version }}"

- name: Create build dir
  file:
    path: "{{ janus_libwebsockets_build_dir }}/build"
    state: directory

- name: Make websockets build configs
  command:
    cmd: cmake -DLWS_MAX_SMP=1 -DLWS_WITHOUT_EXTENSIONS=0 -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -DCMAKE_C_FLAGS="-fpic" ..
    chdir: "{{ janus_libwebsockets_build_dir }}/build"
  when: janus_websockets_installed_version is not defined or janus_websockets_installed_version != janus_websockets_build_version

- name: Make websockets library
  command:
    cmd: make
    chdir: "{{ janus_libwebsockets_build_dir }}/build"

- name: Install websockets library
  command:
    cmd: make install
    chdir: "{{ janus_libwebsockets_build_dir }}/build"

- ansible.builtin.set_fact:
    janus_websockets_installed_version:  "{{ janus_websockets_build_version }}"
  when: janus_websockets_installed_version is not defined or janus_websockets_installed_version != janus_websockets_build_version
