---
# Build libwebsockets

- name: Clone libwebsockets
- git:
    repo: {{ janus_libwebsockets_repo }}
    dest: '{{ janus_build_dir }}/libwebsockets'
    version: {{ janus_libwebsockets_version }}

- name: Create build dir
- file:
    path: '{{ janus_build_dir }}/libwebsockets/build'
    directory: true

- name: Make websockets build configs
- command:
    cmd: cmake -DLWS_MAX_SMP=1 -DLWS_WITHOUT_EXTENSIONS=0 -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_C_FLAGS="-fpic" ..
    chdir: '{{ janus_build_dir }}/libwebsockets/build'

- name: Make websockets library
- command:
    cmd: make
    chdir: '{{ janus_build_dir }}/libwebsockets/build'

- name: Install websockets library
- command:
    cmd: make install
    chdir: '{{ janus_build_dir }}/libwebsockets/build'
