---
# tasks file for ansible-role-janus-gateway
- name: Install platform dependencies
  import_tasks: dependencies.yml
  tags:
    janus-gateway

# Build notes
# Libs conforming to Debian Multiarch are installed to /usr/local/lib/$(gcc -dumpmachine)/
# https://wiki.debian.org/Multiarch

- name: Register gcc machine arch
  command:
    cmd: gcc -dumpmachine
  register: gcc_dumpmachine
  changed_when: False # disable idempotency check (expected to always run)

- ansible.builtin.set_fact:
    gcc_dumpmachine: "{{ gcc_dumpmachine.stdout }}"

- name: Create workspace
  ansible.builtin.file :
    path: "{{ janus_workspace_dir }}"
    state: directory

- name: Install libnice
  import_tasks: libnice.yml
  tags:
    janus-gateway

- name: Install usrsctp
  import_tasks: usrsctp.yml
  tags:
    janus-gateway

- name: Install libwebsockets
  import_tasks: libwebsockets.yml
  tags:
    janus-gateway

- name: Install libsrtp
  import_tasks: libsrtp.yml
  tags:
    janus-gateway

- name: Install janus-gateway
  import_tasks: janus.yml
  tags:
    janus-gateway

# - name: Create workspace
#   ansible.builtin.file :
#     path: "{{ janus_workspace_dir }}"
#     state: absent