---
# Build notes
# Libs conforming to Debian Multiarch are installed to /usr/local/lib/$(gcc -dumpmachine)/
# https://wiki.debian.org/Multiarch
- name: Generate api secrets
  ansible.builtin.set_fact:
    janus_api_secret: "{{ lookup('password', '.tmp/janus_api_secret length=42 chars=ascii_letters') }}"
    janus_token_auth_secret: "{{ lookup('password', '.tmp/janus_token_auth_secret length=42 chars=ascii_letters') }}"
    janus_admin_secret: "{{ lookup('password', '.tmp/janus_admin_secret length=42 chars=ascii_letters') }}"
    cacheable: yes
  when: not janus_api_secret or not janus_token_auth_secret or not janus_admin_secret

- name: Create janus user
  become: true
  ansible.builtin.user:
    name: "{{ janus_user }}"
    shell: /bin/bash
    groups: video
    append: yes

- name: Build janus-gateway from source
  import_tasks: janus.yml
  tags:
    janus-gateway
  when: janus_upgrade_available

- name: Render janus-gateway config templates
  become: true
  ansible.builtin.template:
    mode: 0664
    src: "{{ item.value }}"
    dest: "{{ janus_conf_dir }}/{{ item.value }}"
  with_dict: "{{ janus_conf_template }}"

- name: Janus systemd unit
  import_tasks: systemd.yml
  tags:
    janus-gateway
