---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian10

provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
  
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - destroy