---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian10
    image: debian:buster

provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      gathering: smart
      fact_caching: jsonfile
      fact_caching_connection: /tmp/facts_cache
      fact_caching_timeout: 7200
verifier:
  name: ansible
  
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - destroy